### PR TITLE
Brief common edits

### PR DESCRIPTION
**Pull request by aeifn**

### CODE REVIEW

**Comment by wesley974** [comment]
No need capitals letter in h1, the library I use update the title automatically in capitals...

**Comment by aeifn** [comment]
> No need capitals letter in h1, the library I use update the title automatically in capitals...

source text should be correct not depending on library,
while .toUpperCase will work well on mixed case too

**Comment by wesley974** [comment]
And this jumpstart, keep in mind it will be more for end users, I mean essentially users not dev :)
That's why I don't need to explain how to follow -current.

**Comment by wesley974** [comment]
Anyway, thank you very much for this first try.
Please continue LOL

**Pull request merged**
